#!/usr/bin/env bash
last_pwd=$PWD

# config
export TEMPLATES_HOME=$DOTFILES_HOME/templates

cd $DOTFILES_HOME

# load shell functions
for f in bashrc/*.sh; do
	source $f
done

cd $last_pwd

export PATH=.:$HOME/.local/bin:$PATH
